### ISSUE TITLE
Fallback chain

### ISSUE THREAD

**Issue by zbraniecki** [XAMPPRocky/fluent-templates#1]
Hi! Congrats on the release and thank you for the project, it's exciting!

Reading through the docs I noticed that you use `fallback_language` as the "language to fallback on".

I would recommend sticking a bit closer to the Fluent high-level API model of lazy iterators with fallback chains.
In other words, if a message is missing in user requested locale, the next locale to try shouldn't be hardcoded, but rather follow user requested fallback chain.

That allows for user to specify `["es-CL', "es", "fr", "it", "en"]` chain fluidly, rather than ending up with `["es-CL", "en"]`.

This is important to devalue `en` as "catch all" which is a very western-centric POV, but it also allows for microlocales - like `es-CL` may be just used to provide 10% of strings needed to override over generic `es`.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I'm definitely open to changing it from a single entry to a list of entries.
