### ISSUE TITLE
How to determine available translations

### ISSUE THREAD

**Issue by technic** [XAMPPRocky/fluent-templates#15]
The list of available translation is determined from the `locales` directory (for `StaticLoader`).
Is there a way to access this list from the program? 
Basically when user asks for some language with `Accept-Language` http header I need to know whether I have that language and provide some fallback otherwise. There is a fallback option in `static_loader!`, and also fallback**s** vec in the struct. I don't understand how is it supposed to work?

**Comment by technic** [comment]
I can expose the lists of languages as read-only property of the `Loader`. @XAMPPRocky, what do you think?
I will work on the PR if you give me some hints how fluent fallback work.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! A PR is more than welcome. `ArcLoader` already has a method to expose the available locales so having it in `Loader` makes sense.

**Comment by technic** [comment]
Thanks a lot for your kind answers!
