### ISSUE TITLE
message translated with LOCALES.lookup_complete() contains unexpected extra characters around place-ables

### ISSUE THREAD

**Issue by RustyJoeM** [XAMPPRocky/fluent-templates#21]
Hello,

i'm trying to write simple wrapper for my app to allow translation to a language changeable during runtime.

When I try to get the translation, the args are filled into the ftl string, and i get the translated result, but it contains extra "wrapper" characters around every place-able.

FTL file contents:

```
# $tokens (String) - Number of tokens on input.
# $values (String) - Number of values on input.
valid-count-mismatch =
    Number of tokens is not equal to number of values on input!
    Tokens: { $tokens }
    Values: { $values }
```

Code being executed:

```rust
type ArgsMap<'m> = HashMap<String, FluentValue<'m>>;

fn translate(text_id: &str, args: Option<&ArgsMap>) -> String {
    let lang_code = current_lang().to_lang_code();
    if let Some(li) = LANG_IDS.get(&lang_code) {
        println!("LanguageIdentifier:\n\t{:?}", li);
        println!("text_id:\n\t{:?}", text_id);
        println!("args:\n\t{:?}", args);
        let translated = &*LOCALES.lookup_complete(&li, text_id, args);
        println!("translated:\n\t{}", translated);
        println!("translated debug:\n\t{:?}", translated);
        return translated.to_string();
    }
    text_id.to_string()
}
```

Console output (please note extra characters around two place-ables on last line of printout):

```
LanguageIdentifier:
        LanguageIdentifier { language: Language(Some("en")), script: None, region: Some(Region("US")), variants: None }
text_id:
        "valid-count-mismatch"
args:
        Some({"values": String("1"), "tokens": String("3")})
translated:
        Number of tokens is not equal to number of values on input!
Tokens: ⁨3⁩
Values: ⁨1⁩
translated debug:
        "Number of tokens is not equal to number of values on input!\nTokens: \u{2068}3\u{2069}\nValues: \u{2068}1\u{2069}"
```

Windows console shows chars as sort graphical noise (console line `translated:`).
Github here does not show these above... It causes problem on windows, as GUI dialogs etc.
It is visible in debug dump on next line (`translated debug:`) - \u{2068} - \u{2069}.

Is this place-able wrapper intentionally done by the LOOKUP methods? If so, can it be disabled? 
If not, what could be causing this behavior?...

I do NOT need any type specific extra  localization/internationalization features, so limiting myself to string is not a problem...
I'm not sure whether other argument types (thank String shown above) have same issue. I tried to work with generic argument map originally, that could allow numbers etc. (via Into<FluentValue>), but failed to pass them around as parameters of methods due to being Rust beginner...

All files (FTL, rust .rs, ...) are UTF-8 encoded, LF line endings.

Thank you for tips/guidelines...

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Yes, I believe this is an intentional feature of fluent. Those are isolating marks that are used for allowing bidirectional text. You can disable this with `FluentBundle::set_use_isolating`. See the below example.

```rust
static_loader! {
    static LOCALES = {
        locales: "./tests/locales",
        fallback_language: "en-US",
        // Removes unicode isolating marks around arguments
        customise: |bundle| bundle.set_use_isolating(false),
    };
}
```

**Comment by RustyJoeM** [comment]
thank you for help and prompt response!

disadvantage of interconnected web of crates ~ sometimes beginners fail to identify the suspect correctly! :)

**Comment by XAMPPRocky** [comment]
No worries, I was also confused when I first saw it. I'll add a note about it to the README.
