### ISSUE TITLE
`arc-swap` yanked; `fluent_templates 0.5.0` fails to build

### ISSUE THREAD

**Issue by wyattjsmith1** [XAMPPRocky/fluent-templates#22]
Hi, it looks like `fluent_templates` relies on `arc-swap = "^0.4.7"`, but many recent `arc-swap` versions have been yanked: https://docs.rs/arc-swap/0.4.7/arc_swap/index.html. This is causing build issues such as:

```
error: failed to select a version for the requirement `arc-swap = "^0.4.7"`
  candidate versions found which didn't match: 1.1.0, 0.4.1, 0.4.0, ...
  location searched: crates.io index
required by package `fluent-templates v0.5.0`
    ... which is depended on by ...
```

I think the proper solution is to change the `arc-swap` dependency to either `0.4.1` or `1.1.0`

**Comment by XAMPPRocky** [comment]
Thank you for your issue! There has been a patch to 0.4 so it should build now if you run cargo update. In the meantime I’ll make a new release

**Comment by XAMPPRocky** [comment]
Closing as I've updated master with the new dependency.
