### ISSUE TITLE
Allow arguments to be &'static str

### ISSUE THREAD

**Issue by kgv** [XAMPPRocky/fluent-templates#23]
I suggest сhange signature `lookup_complete(... args: Option<&HashMap<String, FluentValue>>) -> String`
to something like `lookup_complete<T: AsRef<str> + 'static>(... args: Option<&HashMap<T, FluentValue>>) -> String`.
This will remove unnecessary allocations from user code.

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=215ac629b3bcd0b14125ca1ecd7d382a)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! That seems like good idea to me, as long you can continue to provide `HashMap<String, V>`. If you’d like to contribute I’d accept a PR implementing this, otherwise I might work on it later in the week.
