### ISSUE TITLE
Static Loader causes doc tests to fail in library crates in a workspace

### ISSUE THREAD

**Issue by ecton** [XAMPPRocky/fluent-templates#3]
It appears that static_loader! is generating doc tests, and those doc tests fail.

* Create new project
* Add fluent-templates dependency
* Add this to main.rs:

```rust
fluent_templates::static_loader! {
    // Declare our `StaticLoader` named `LOCALES`.
    static LOCALES = {
        // The directory of localisations and fluent resources.
        locales: "./locales",
        // The language to falback on if something is not present.
        fallback_language: "en-US",
    };
}
```

* Create a folder named locales
* Run `cargo test`

This error is printed:

```
   Compiling fluent-templates-test v0.1.0 (C:\Users\jon\repos\fluent-templates-test)
error: proc macro panicked
 --> src\main.rs:1:1
  |
1 | / fluent_templates::static_loader! {
2 | |     // Declare our `StaticLoader` named `LOCALES`.
3 | |     static LOCALES = {
4 | |         // The directory of localisations and fluent resources.
... |
8 | |     };
9 | | }
  | |_^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }

error: aborting due to previous error

error: could not compile `fluent-templates-test`.
```

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However I don't think that's the case. I've linked the entire proc macro code below. I also can't replicate this, so I assume it must be on your end. However I think that error message is pretty unclear and could better show you that.

https://github.com/XAMPPRocky/fluent-templates/blob/a5aaea8bd8472b063033355a855e16112d1cd12f/macros/src/lib.rs#L190-L229

**Comment by ecton** [comment]
Ah you're right, it's not quite that simple. It only fails when static_loader is used in a library crate inside of a workspace. Here's the repo: https://github.com/ecton/fluent-templates-test

If you clone it, and run `cargo test` and see it produce the error I mentioned. If you run `cargo test --lib` it will work because it skips the doc tests passed. However, after trying `cargo expand` I notice that you're absolutely correct: no documentation tests. But it still fails the documentation testing pass, which makes me think that the `cargo test --doc` environment is different than the normal environment somehow, but only for projects in a workspace.

**Comment by XAMPPRocky** [comment]
That's the same problem, the path in your case is incorrect. I've just put out `0.5.5` as a patch which will give you a much clearer error message about what is going on.

**Comment by ecton** [comment]
@XAMPPRocky I don't think it's valid behavior to have it build but then fail doc tests. `cargo build` thinks the path is fine, `cargo test --lib` thinks the path is fine, `cargo test --doc` fails.

**Comment by XAMPPRocky** [comment]
@ecton Have you updated your test to use `0.5.5` and checked the error message?

**Comment by ecton** [comment]
Using my repo, running as is:

```
C:\Users\jon\repos\fluent-templates-test>cargo build
    Blocking waiting for file lock on build directory
   Compiling fluent-templates-test v0.1.0 (C:\Users\jon\repos\fluent-templates-test\fluent-templates-test)                                                                                                        
    Finished dev [unoptimized + debuginfo] target(s) in 3.82s                                                                                                                                                     

C:\Users\jon\repos\fluent-templates-test>cargo test
    Blocking waiting for file lock on build directory
    Finished test [unoptimized + debuginfo] target(s) in 0.47s                                                                                                                                                    
     Running target\debug\deps\fluent_templates_test-24dea5207215638a.exe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests fluent-templates-test
error: Couldn't read locales directory, this path should be relative to your crate's `Cargo.toml`.
 --> C:\Users\jon\repos\fluent-templates-test\fluent-templates-test\src\lib.rs:3:18
  |
3 |         locales: "./fluent-templates-test/src/locales",
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: test failed, to rerun pass '--doc'
```

`cargo build` succeeds, but cargo test prints that error. I cannot find a value for the string where it compiles in all situations.

**Comment by ecton** [comment]
If the error message contained the resolved path it was trying to locate, it would help debug this further.

**Comment by ecton** [comment]
@XAMPPRocky I know the problem now. I cloned the repo locally and started tinkering, adding the std::env::current_dir() to the error message.

When running `cargo build` and `cargo test --lib`, the current working dir is the workspace dir. However, when running `cargo test --doc` the current working dir is the crate dir itself.

I think the fix ultimately will be referencing the cargo env var CARGO_MANIFEST_DIR

```
        let workspace_path = std::path::PathBuf::from(
            std::env::var("CARGO_MANIFEST_DIR").unwrap_or("./".to_owned()),
        );
```

When I do this I can get past the error checking code:

```
        let locales_directory_path = workspace_path.join(locales_directory.value());

        if std::fs::metadata(&locales_directory_path).is_err() {
            return Err(syn::Error::new(locales_directory.span(), &format!("Couldn't read locales directory, this path should be relative to your crate's `Cargo.toml`. Looking for: {:?}", locales_directory_path)));
        }
```

Working on a PR for you.
