### ISSUE TITLE
Have Loader::lookup_complete return Option<String>

### ISSUE THREAD

**Issue by jamolnng** [XAMPPRocky/fluent-templates#32]
Having `Loader::lookup_complete` and subsequently `lookup_with_args` and `lookup` will let the user choose what to do in case the fluent template is not found with the given language identifier or the fallback identifier

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Seems reasonable to me, if someone wants to contribute a PR to fix it, it's always welcome.

**Comment by jamolnng** [comment]
will work on it, seems like a quick change

**Comment by jamolnng** [comment]
Closed https://github.com/XAMPPRocky/fluent-templates/pull/33
