### ISSUE TITLE
Return Result instead of panic when looking up?

### ISSUE THREAD

**Issue by hongquan** [XAMPPRocky/fluent-templates#49]
Currently, the `lookup_xxx` functions, when encoutering bad FTL message (wrong syntax, for example), it just [panic](https://github.com/XAMPPRocky/fluent-templates/blob/66f53a7fc1e165012897861888647f75765a1d50/src/loader/shared.rs#L35).
Could you please make the function return `Result`, instead of panic?

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This has been resolved by #47 which adds `try_` variants which return Options instead of panicking
