### ISSUE TITLE
Consider removing the generics on `Loader` methods.

### ISSUE THREAD

**Issue by mscofield0** [XAMPPRocky/fluent-templates#81]
Reason for removing would be so that loaders can be used as params (`&dyn Loader`) and so that they can be stored in `Box`es and not have it spew out "not object-safe" errors.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However we already have an issue about this so I'm going to close this a duplicate of https://github.com/XAMPPRocky/fluent-templates/issues/39
